import type { Metadata } from 'next'
import PageLayout from '@/components/features/layout/PageLayout'
import TopBar from '@/components/features/navigation/TopBar'
import WalletContextProvider from '@/providers/WalletContextProvider'
import MuiProvider from '@/providers/MuiProvider'
import '@/app/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <MuiProvider>
          <WalletContextProvider>
            <TopBar />
            <PageLayout>{children}</PageLayout>
          </WalletContextProvider>
        </MuiProvider>
      </body>
    </html>
  )
}
